name: Django CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Docker
      run: |
        source "$ENV_FILE"
        docker-compose up -d
      env:
        ENV_FILE: .env
        PROJECT_NAME: brasil.io
        DOCKER_COMPOSE_FILE: docker-compose.yml
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev-requirements.txt
    - name: Migrate and Update Data
      run: |
        python manage.py migrate
    - name: Run Tests
      run: |
        python manage.py test
